import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  OneToMany,
  JoinColumn,
} from 'typeorm';
import { User }      from './User';
import { OrderItem } from './OrderItem';

export enum OrderStatus {
  PENDING    = 'pending',
  PAID       = 'paid',
  PROCESSING = 'processing',
  SHIPPED    = 'shipped',
  DELIVERED  = 'delivered',
  REFUNDED   = 'refunded',
  CANCELLED  = 'cancelled',
  FAILED     = 'failed',
}

@Entity('orders')
export class Order {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToOne(() => User, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'user_id' })
  user!: User;

  @Column({ type: 'enum', enum: OrderStatus, default: OrderStatus.PENDING })
  status!: OrderStatus;

  @Column({ type: 'numeric', precision: 12, scale: 2 })
  subtotal!: number;

  @Column({ type: 'numeric', precision: 12, scale: 2, default: 0 })
  tax!: number;

  @Column({ type: 'numeric', precision: 12, scale: 2 })
  total!: number;

  @Column({ length: 3, default: 'GHS' })
  currency!: string;

  @Column({ type: 'jsonb' })
  shippingAddress!: {
    fullName:     string;
    addressLine1: string;
    addressLine2?: string;
    city:         string;
    state:        string;
    postalCode:   string;
    country:      string;
    phone:        string;
  };

  // Paystack transaction reference (generated by us)
  @Column({ nullable: true, unique: true })
  paystackReference!: string;

  // Paystack transaction ID (returned by Paystack after payment)
  @Column({ nullable: true })
  paystackTransactionId!: string;

  // URL to redirect customer to complete payment
  @Column({ nullable: true })
  paymentUrl!: string;

  @OneToMany(() => OrderItem, (item) => item.order, { cascade: true })
  items!: OrderItem[];

  @CreateDateColumn()
  placedAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}