import express, { Express } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import swaggerUi from 'swagger-ui-express';
import { RegisterRoutes } from './routes'; // generated by tsoa
import { errorHandler } from './middlewares/errorHandler';
import { env } from './config/env';

const swaggerDocument = require('../src/public/swagger.json');

export function createApp(): Express {
  const app = express();

  // Security & utilities
  app.use(helmet());
  app.use(cors({ origin: env.FRONTEND_URL }));
  app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));

  // Raw body for Stripe webhooks (must come before express.json)
  app.use('/payments/webhook', express.raw({ type: 'application/json' }));

  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));

  // Swagger UI
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

  // tsoa-generated routes
  RegisterRoutes(app);

  // Global error handler (must be last)
  app.use(errorHandler);

  return app;
}
